### ISSUE TITLE
Uncaught Error: Class 'Aws\Signature\SignatureV4' not found

### ISSUE THREAD

**Issue by timblanq** [deeparteffects/sdk-php#1]
I tried to use your wonderful API, but i just got an error saying:
`Uncaught Error: Class 'Aws\Signature\SignatureV4' not found`
Could you please help me fixing this issue?

**Comment by clarrat** [comment]
Please install necessary dependencies with composer.

**Comment by timbogdanov** [comment]
@clarrat i have this issue as well. not sure it belong here tho. Ran compose i and update, still gives this error

Class 'Aws\\Common\\Signature\\SignatureV4' not found
